# Generated by Django 3.2.16 on 2025-04-05 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('hotelUid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('address', models.CharField(max_length=256, verbose_name='Полный адрес')),
                ('price_for_nigth', models.PositiveIntegerField(verbose_name='Стоимость за ночь')),
            ],
            options={
                'verbose_name': 'отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['-price_for_nigth', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyModel',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Имя пользователя')),
                ('total_reservations', models.PositiveIntegerField(default=0, verbose_name='Число бронирований')),
                ('status', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BRONZE', max_length=10, verbose_name='Статус лояльности')),
            ],
            options={
                'verbose_name': 'программа лояльности',
                'verbose_name_plural': 'Программы лояльности',
            },
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('reservationUid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('CANCELED', 'Canceled')], default='SUCCESS', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.hotelmodel', verbose_name='Название отеля')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.loyaltymodel', verbose_name='Имя пользователя.')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
