# Generated by Django 3.2.16 on 2025-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма бронирования'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='end_date',
            field=models.DateField(verbose_name='Конец бронирования'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='start_date',
            field=models.DateField(verbose_name='Начало бронирования'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('CANCELED', 'Canceled')], default='SUCCESS', max_length=10, verbose_name='Статус'),
        ),
    ]
