# Generated by Django 3.2.16 on 2025-04-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservationmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
